apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespace.yaml

namespace: todopro-staging

commonLabels:
  environment: staging

images:
  - name: todopro-frontend
    newTag: develop
  - name: todopro-backend
    newTag: develop

patchesStrategicMerge:
  - patches/configmap-patch.yaml

replicas:
  - name: frontend
    count: 1
  - name: backend
    count: 1