apiVersion: v1
kind: ConfigMap
metadata:
  name: todopro-config
  namespace: todopro
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "todo_db"
  REACT_APP_API_URL: "http://backend-service:8000/api"