apiVersion: v1
kind: Secret
metadata:
  name: todopro-secrets
  namespace: todopro
type: Opaque
stringData:
  DB_USERNAME: "todo_user"
  DB_PASSWORD: "todo_password"
  APP_KEY: "base64:SGVsbG9Xb3JsZEhlbGxvV29ybGRIZWxsb1dvcmxkSGVsbG9Xb3JsZA=="
  JWT_SECRET: "your-jwt-secret-key"